server:
    port: 80
    servlet:
        session:
            timeout: 30m
spring:
    datasource:
        username: username
        password: password
        url: jdbc:mysql://127.0.0.1:3306/restaurant?useSSL=false&CharacterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        driver-class-name: com.mysql.cj.jdbc.Driver
        hikari:
            max-lifetime: 900000
            minimum-idle: 10
    jpa:
        # 自动生成表，不过还是建议手动建
        generate-ddl: true
        database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    jackson:
        date-format: yyyy-MM-dd HH:mm:ss
        time-zone: GMT+8
    redis:
        password: 123456
        port: 6379
        host: 127.0.0.1
        database: 0
        jedis:
            pool:
                # 连接池最大连接数（使用负值表示没有限制）
                max-active: 8
                # 连接池最大阻塞等待时间（使用负值表示没有限制）
                max-wait: -1ms
                # 连接池中的最大空闲连接
                max-idle: 8
                # 连接池中的最小空闲连接
                min-idle: 1
        # 连接超时时间（毫秒）默认是2000ms
        timeout: 2000ms
    cache:
        redis:
            key-prefix: homework
            time-to-live: 30m
fdfsUrl: http://127.0.0.1:10000